const brands = [ 
  {value: 'Abarth', label: 'Abarth' },
  {value: 'Alfa Romeo', label: 'Alfa Romeo' },
  {value: 'Aston Martin', label: 'Aston Martin' },
  {value: 'Audi', label: 'Audi' },
  {value: 'Bentley', label: 'Bentley' },
  {value: 'BMW', label: 'BMW' },
  {value: 'Cadillac', label: 'Cadillac' },
  {value: 'Caterham', label: 'Caterham' },
  {value: 'Chevrolet', label: 'Chevrolet' },
  {value: 'Citroen', label: 'Citroen' },
  {value: 'Dacia', label: 'Dacia' },
  {value: 'Ferrari', label: 'Ferrari' },
  {value: 'Fiat', label: 'Fiat' },
  {value: 'Ford', label: 'Ford' },
  {value: 'Honda', label: 'Honda' },
  {value: 'Infiniti', label: 'Infiniti' },
  {value: 'Isuzu', label: 'Isuzu' },
  {value: 'Iveco', label: 'Iveco' },
  {value: 'Jaguar', label: 'Jaguar' },
  {value: 'Jeep', label: 'Jeep' },
  {value: 'Kia', label: 'Kia' },
  {value: 'KTM', label: 'KTM' },
  {value: 'Lada', label: 'Lada' },
  {value: 'Lamborghini', label: 'Lamborghini' },
  {value: 'Lancia', label: 'Lancia' },
  {value: 'Land Rover', label: 'Land Rover' },
  {value: 'Lexus', label: 'Lexus' },
  {value: 'Lotus', label: 'Lotus' },
  {value: 'Maserati', label: 'Maserati' },
  {value: 'Mazda', label: 'Mazda' },
  {value: 'Mercedes-Benz', label: 'Mercedes-Benz' },
  {value: 'Mini', label: 'Mini' },
  {value: 'Mitsubishi', label: 'Mitsubishi' },
  {value: 'Morgan', label: 'Morgan' },
  {value: 'Nissan', label: 'Nissan' },
  {value: 'Opel', label: 'Opel' },
  {value: 'Peugeot', label: 'Peugeot' },
  {value: 'Piaggio', label: 'Piaggio' },
  {value: 'Porsche', label: 'Porsche' },
  {value: 'Renault', label: 'Renault' },
  {value: 'Rolls-Royce', label: 'Rolls-Royce' },
  {value: 'Seat', label: 'Seat' },
  {value: 'Skoda', label: 'Skoda' },
  {value: 'Smart', label: 'Smart' },
  {value: 'SsangYong', label: 'SsangYong' },
  {value: 'Subaru', label: 'Subaru' },
  {value: 'Suzuki', label: 'Suzuki' },
  {value: 'Tata', label: 'Tata' },
  {value: 'Tesla', label: 'Tesla' },
  {value: 'Toyota', label: 'Toyota' },
  {value: 'Volkswagen', label: 'Volkswagen' },
  {value: 'Volvo', label: 'Volvo' },
]
export default brands